import React, { useState, useEffect, useCallback, useRef } from 'react';
import { Plus, Trash2, Edit, Save, X, Download, Upload, Share2, Sun, Moon } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Share } from '@capacitor/share';
import { Filesystem, Directory, Encoding } from '@capacitor/filesystem';
import * as htmlToImage from 'html-to-image';

// --- Grade to Point Mapping ---
const gradePoints = {
  'O': 10, 'A+': 10, 'A': 9, 'B+': 8, 'B': 7, 'C': 6, 'P': 5, 'F': 0, 'FAIL': 0,
};

// --- Custom Alert Component ---
const CustomAlert = ({ message, onClose }) => {
  if (!message) return null;
  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <motion.div
        className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-xl w-full max-w-sm text-center"
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
      >
        <h3 className="text-lg font-bold text-gray-900 dark:text-white">{message.title}</h3>
        <p className="text-sm text-gray-600 dark:text-gray-300 mt-2 mb-6">{message.body}</p>
        <button onClick={onClose} className="bg-blue-500 text-white font-bold py-2 px-6 rounded-lg w-full hover:bg-blue-600 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-400">
          OK
        </button>
      </motion.div>
    </div>
  );
};

// --- Report Card Component for Image Export ---
const ReportCard = React.forwardRef(({ semesters, cgpa, totalCredits }, ref) => (
    <div ref={ref} className="p-8 bg-gray-50 text-gray-800" style={{width: '600px'}}>
        <div className="text-center mb-6">
            <h1 className="text-3xl font-bold text-gray-900">CGPA Report</h1>
            <p className="text-md text-gray-600">Generated by CGPA Tracker</p>
        </div>
        <div className="bg-indigo-600 text-white p-6 rounded-xl shadow-lg mb-6 flex justify-around items-center">
            <div>
                <p className="text-sm uppercase font-semibold opacity-80">Overall CGPA</p>
                <p className="text-5xl font-bold">{cgpa}</p>
            </div>
            <div className="border-l-2 border-indigo-400 h-16"></div>
            <div>
                <p className="text-sm uppercase font-semibold opacity-80">Total Credits</p>
                <p className="text-5xl font-bold">{totalCredits}</p>
            </div>
        </div>
        <div className="space-y-4">
            {semesters.map((semester, index) => (
                <div key={index} className="bg-white p-4 rounded-lg shadow">
                    <div className="flex justify-between items-center">
                        <h3 className="font-bold text-lg">{semester.name}</h3>
                        <div>
                           <span className="font-bold text-xl text-indigo-600">{semester.sgpa}</span>
                           <span className="text-xs text-gray-500 ml-1">SGPA</span>
                        </div>
                    </div>
                </div>
            ))}
        </div>
    </div>
));


// --- Main App Component ---
export default function App() {
  const [semesters, setSemesters] = useState([]);
  const [modalVisible, setModalVisible] = useState(false);
  const [currentSemester, setCurrentSemester] = useState(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editIndex, setEditIndex] = useState(null);
  const [alertMessage, setAlertMessage] = useState(null);
  const [theme, setTheme] = useState('light');
  const reportCardRef = useRef(null);

  // --- Data Persistence ---
  useEffect(() => {
    try {
      const storedSemesters = localStorage.getItem('@semesters_data');
      if (storedSemesters) setSemesters(JSON.parse(storedSemesters));

      const storedTheme = localStorage.getItem('theme') || 'light';
      setTheme(storedTheme);
    } catch (e) {
      console.error("Failed to load data from storage", e);
      setAlertMessage({ title: "Load Error", body: "Could not load your saved data." });
    }
  }, []);

  useEffect(() => {
    try {
      localStorage.setItem('@semesters_data', JSON.stringify(semesters));
    } catch (e) {
      console.error("Failed to save data to storage", e);
      setAlertMessage({ title: "Save Error", body: "Could not save your changes." });
    }
  }, [semesters]);

  useEffect(() => {
    document.documentElement.classList.remove('light', 'dark');
    document.documentElement.classList.add(theme);
    localStorage.setItem('theme', theme);
  }, [theme]);

  // --- Calculation Logic ---
  const calculateSGPA = useCallback((subjects) => {
    if (!subjects || subjects.length === 0) return '0.00';
    let totalPoints = 0;
    let totalCredits = 0;
    subjects.forEach(subject => {
      const credits = parseFloat(subject.credits);
      const grade = subject.grade.toUpperCase();
      const point = gradePoints[grade] !== undefined ? gradePoints[grade] : 0;
      if (!isNaN(credits) && credits > 0) {
        totalPoints += credits * point;
        totalCredits += credits;
      }
    });
    return totalCredits === 0 ? '0.00' : (totalPoints / totalCredits).toFixed(2);
  }, []);

  const calculateCGPA = useCallback(() => {
    let grandTotalPoints = 0;
    let grandTotalCredits = 0;
    semesters.forEach(semester => {
      semester.subjects.forEach(subject => {
        const credits = parseFloat(subject.credits);
        if (!isNaN(credits) && credits > 0) {
          const point = gradePoints[subject.grade.toUpperCase()] || 0;
          grandTotalPoints += credits * point;
          grandTotalCredits += credits;
        }
      });
    });
    return grandTotalCredits === 0 ? '0.00' : (grandTotalPoints / grandTotalCredits).toFixed(2);
  }, [semesters]);

  const totalCreditsCompleted = useCallback(() => {
    return semesters.reduce((total, sem) =>
      total + sem.subjects.reduce((semTotal, sub) =>
        semTotal + (parseFloat(sub.credits) || 0), 0), 0);
  }, [semesters]);


  // --- Handlers for Semester Operations ---
  const handleAddNewSemester = () => {
    setCurrentSemester({
      name: `Semester ${semesters.length + 1}`,
      subjects: [{ name: '', credits: '', grade: '' }],
    });
    setIsEditing(false);
    setModalVisible(true);
  };

  const handleEditSemester = (index) => {
    setCurrentSemester(JSON.parse(JSON.stringify(semesters[index])));
    setIsEditing(true);
    setEditIndex(index);
    setModalVisible(true);
  };

  const handleSaveSemester = () => {
    if (currentSemester.subjects.some(s => !s.name.trim() || !s.credits || !s.grade)) {
      setAlertMessage({ title: "Incomplete Fields", body: "Please fill all details for each subject." });
      return;
    }
    const sgpa = calculateSGPA(currentSemester.subjects);
    const updatedSemester = { ...currentSemester, sgpa };

    setSemesters(prev => isEditing ? prev.map((s, i) => i === editIndex ? updatedSemester : s) : [...prev, updatedSemester]);
    setModalVisible(false);
  };

  const handleDeleteSemester = (index) => {
    setSemesters(prev => prev.filter((_, i) => i !== index));
  };

  // --- Handlers for Subject Operations within the Modal ---
  const handleSubjectChange = (index, field, value) => {
    const newSubjects = [...currentSemester.subjects];
    newSubjects[index][field] = value;
    setCurrentSemester({ ...currentSemester, subjects: newSubjects });
  };

  const handleAddSubject = () => {
    setCurrentSemester(prev => ({...prev, subjects: [...prev.subjects, { name: '', credits: '', grade: '' }]}));
  };

  const handleDeleteSubject = (index) => {
    if (currentSemester.subjects.length > 1) {
      setCurrentSemester(prev => ({...prev, subjects: prev.subjects.filter((_, i) => i !== index)}));
    } else {
      setAlertMessage({ title: "Action Not Allowed", body: "A semester must have at least one subject." });
    }
  };

  // --- Data Management Handlers ---
  const handleExport = async () => {
      if (!reportCardRef.current || semesters.length === 0) {
        setAlertMessage({ title: "No Data", body: "There is no data to export." });
        return;
      }
      
      try {
        const dataUrl = await htmlToImage.toPng(reportCardRef.current, { cacheBust: true });

        await Share.share({
          title: 'My CGPA Report',
          files: [dataUrl],
          dialogTitle: 'Share or Save Report Image'
        });

      } catch (error) {
        console.error('oops, something went wrong!', error);
        setAlertMessage({ title: "Export Error", body: "Could not generate or share the image." });
      }
  };


  const handleImport = (event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const importedData = JSON.parse(e.target.result);
          if (Array.isArray(importedData)) {
            setSemesters(importedData);
            setAlertMessage({ title: "Success", body: "Data imported successfully." });
          } else {
            throw new Error("Invalid data format.");
          }
        } catch (error) {
          setAlertMessage({ title: "Import Error", body: "Could not import data. The file may be corrupt or in the wrong format." });
        }
      };
      reader.readAsText(file);
    }
    event.target.value = null;
  };

  const handleShareCGPA = () => {
    const cgpa = calculateCGPA();
    const shareText = `Hey! I'm tracking my academic progress and my current CGPA is ${cgpa}.`;
    if (navigator.share) {
      navigator.share({ title: 'My CGPA Progress', text: shareText }).catch(console.error);
    } else {
      navigator.clipboard.writeText(shareText);
      setAlertMessage({ title: "Copied!", body: "Your progress has been copied to the clipboard." });
    }
  };

  const EmptyState = () => (
    <div className="text-center py-20 px-6">
       <svg className="mx-auto h-24 w-24 text-gray-300 dark:text-gray-600" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
        <path fillRule="evenodd" d="M3 6a3 3 0 013-3h12a3 3 0 013 3v12a3 3 0 01-3 3H6a3 3 0 01-3-3V6zm3-1a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V6a1 1 0 00-1-1H6zm1.5 8.707a.5.5 0 01.707 0L9.5 15.086l2.793-2.793a.5.5 0 01.707 0l3.5 3.5a.5.5 0 01-.707.707L13 13.586l-2.793 2.793a.5.5 0 01-.707 0L7.207 14.5a.5.5 0 010-.707z" clipRule="evenodd" />
      </svg>
      <h3 className="mt-4 text-xl font-semibold text-gray-800 dark:text-gray-200">No Semesters Added</h3>
      <p className="mt-2 text-md text-gray-500 dark:text-gray-400">Get started by adding your first semester's results.</p>
      <button onClick={handleAddNewSemester} className="mt-6 inline-flex items-center gap-2 bg-blue-500 text-white font-bold py-2 px-4 rounded-lg hover:bg-blue-600 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-400">
        <Plus size={20} /> Add First Semester
      </button>
    </div>
  );

  const modalInputStyle = "w-full bg-gray-100 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-400 transition-all text-gray-900 dark:text-white";

  return (
    <>
      <div style={{position: 'fixed', left: '-9999px', top: '-9999px'}}>
          <ReportCard 
              ref={reportCardRef} 
              semesters={semesters} 
              cgpa={calculateCGPA()} 
              totalCredits={totalCreditsCompleted()}
          />
      </div>
      <div className="bg-gray-100 dark:bg-gray-900 min-h-screen font-sans text-gray-800 dark:text-gray-200 transition-colors">
        <CustomAlert message={alertMessage} onClose={() => setAlertMessage(null)} />
        <div className="container mx-auto p-4 sm:p-6 max-w-4xl">
          <header className="flex justify-between items-center mb-6">
            <h1 className="text-3xl font-extrabold text-gray-900 dark:text-white">CGPA Tracker</h1>
            <div className="flex items-center gap-2">
              <button onClick={() => setTheme(t => t === 'light' ? 'dark' : 'light')} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors">
                {theme === 'light' ? <Moon size={20} /> : <Sun size={20} />}
              </button>
               <button onClick={handleShareCGPA} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"><Share2 size={20} /></button>
              <label className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors cursor-pointer">
                <Upload size={20} />
                <input type="file" accept=".json" onChange={handleImport} className="hidden" />
              </label>
              <button onClick={handleExport} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"><Download size={20} /></button>
            </div>
          </header>

          <motion.div
            className="bg-gradient-to-br from-blue-500 to-indigo-600 p-6 rounded-2xl shadow-lg text-white mb-6"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <div className="flex justify-between items-center">
              <div>
                <p className="text-sm opacity-80 uppercase font-semibold">Overall CGPA</p>
                <p className="text-5xl font-bold tracking-tight">{calculateCGPA()}</p>
              </div>
              <div className="text-right">
                <p className="text-sm opacity-80 uppercase font-semibold">Total Credits</p>
                <p className="text-3xl font-bold">{totalCreditsCompleted()}</p>
              </div>
            </div>
          </motion.div>

          {semesters.length > 0 ? (
            <div className="space-y-4">
              <AnimatePresence>
                {semesters.map((semester, index) => (
                  <motion.div
                    key={index}
                    layout
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    transition={{ duration: 0.3 }}
                    className="bg-white dark:bg-gray-800 rounded-2xl shadow-md p-5 flex items-center gap-4"
                  >
                    <div className="flex-grow">
                      <h3 className="font-bold text-lg text-gray-900 dark:text-white">{semester.name}</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        {semester.subjects.reduce((acc, s) => acc + (parseFloat(s.credits) || 0), 0)} Credits
                      </p>
                    </div>
                    <div className="text-center">
                      <p className="font-bold text-2xl text-indigo-500 dark:text-indigo-400">{semester.sgpa}</p>
                      <p className="text-xs text-gray-500 dark:text-gray-400 uppercase">SGPA</p>
                    </div>
                    <div className="flex gap-2">
                      <button onClick={() => handleEditSemester(index)} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"><Edit size={18} /></button>
                      <button onClick={() => handleDeleteSemester(index)} className="p-2 rounded-full text-red-500 hover:bg-red-100 dark:hover:bg-red-900/50 transition-colors"><Trash2 size={18} /></button>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          ) : (
            <EmptyState />
          )}
        </div>

        <AnimatePresence>
          {modalVisible && (
            <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-40 p-4">
              <motion.div
                className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl w-full max-w-md flex flex-col"
                style={{maxHeight: '90vh'}}
                initial={{ y: 50, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                exit={{ y: 50, opacity: 0 }}
              >
                <div className="p-5 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center">
                  <input
                    type="text"
                    className="text-lg font-bold bg-transparent focus:outline-none w-full text-gray-900 dark:text-white"
                    value={currentSemester?.name}
                    onChange={(e) => setCurrentSemester(prev => ({...prev, name: e.target.value}))}
                  />
                  <button onClick={() => setModalVisible(false)} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"><X size={20} /></button>
                </div>

                <div className="p-5 flex-grow overflow-y-auto space-y-4">
                    {currentSemester?.subjects.map((subject, index) => (
                      <motion.div
                        key={index}
                        layout
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, x: -20 }}
                        className="bg-gray-50 dark:bg-gray-700/50 p-4 rounded-lg relative"
                      >
                         <button onClick={() => handleDeleteSubject(index)} className="absolute top-2 right-2 text-gray-400 hover:text-red-500 p-1 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
                          <Trash2 size={16} />
                        </button>
                        <div className="space-y-3">
                          <div>
                             <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Subject Name</label>
                             <input type="text" placeholder="e.g., Physics" value={subject.name} onChange={e => handleSubjectChange(index, 'name', e.target.value)} className={modalInputStyle} />
                          </div>
                          <div className="grid grid-cols-2 gap-3">
                             <div>
                                <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Credits</label>
                                <input type="number" placeholder="e.g., 4" value={subject.credits} onChange={e => handleSubjectChange(index, 'credits', e.target.value)} className={`${modalInputStyle} text-center`} />
                             </div>
                             <div>
                                <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Grade</label>
                                <input type="text" placeholder="e.g., A+" value={subject.grade} onChange={e => handleSubjectChange(index, 'grade', e.target.value)} className={`${modalInputStyle} text-center uppercase`} />
                             </div>
                          </div>
                        </div>
                      </motion.div>
                    ))}
                </div>

                <div className="p-5 border-t border-gray-200 dark:border-gray-700 space-y-3">
                  <button onClick={handleAddSubject} className="w-full text-center py-2.5 bg-gray-100 dark:bg-gray-700/50 hover:bg-gray-200 dark:hover:bg-gray-700 font-semibold rounded-lg transition-colors text-sm">
                    + Add Another Subject
                  </button>
                  <button onClick={handleSaveSemester} className="w-full text-center py-3 bg-blue-500 hover:bg-blue-600 text-white font-bold rounded-lg transition-colors flex items-center justify-center gap-2">
                    <Save size={18} /> {isEditing ? 'Update Semester' : 'Save Semester'}
                  </button>
                </div>
              </motion.div>
            </div>
          )}
        </AnimatePresence>

        {semesters.length > 0 && (
           <motion.button
            onClick={handleAddNewSemester}
            className="fixed bottom-6 right-6 bg-blue-500 text-white rounded-full p-4 shadow-lg hover:bg-blue-600 transition-transform transform hover:scale-110 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 dark:focus:ring-offset-gray-900 z-30"
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            exit={{ scale: 0 }}
          >
            <Plus size={24} />
          </motion.button>
        )}
      </div>
    </>
  );
}

